### ISSUE TITLE
Notify Admin by tracking user's LinkedIn profile on its any experience changes.

### ISSUE THREAD

**Issue by sarvaiyanidhi** [joemasilotti/railsdevs.com#839]
Need to notify admin on weekly basis on any changes in user's LinkedIn profile related to its experience.

Linkedin profile will be tracked using external service https://nubela.co/proxycurl/

A PR addressing this issue should

- [ ] New table developer_linkedin_profile_details storing all information related to developer's linkedin profile like current_company_name, start_date, title, location. Note, additional fields apart from company name are stored just for information now and can be used later.
- [ ] Script running weekly fetching LinkedIn details and storing in database
- [ ] Script notifying admin on any experience changes in developer's profile every week.

**Comment by joemasilotti** [comment]
Thanks for kicking this off @sarvaiyanidhi!

My only addition is that we will be doing something very similar for GitHub soon. See #779.

And if we could model the new table to handle both somehow that would be great.

**Comment by sarvaiyanidhi** [comment]
Actually, I did see that and had same thought of having single table storing all external information of developer's profile but as it is still in progress so can we come back and refactor to store information later from single table.

Another option, I can create generic table for now to create linkedin information and later on we can migrate Github changes to this table once it is done.

**Comment by joemasilotti** [comment]
I'm happy to go with whatever you think is best. Just wanted to call out the GitHub integration in case it changed how you would structure stuff. :)

**Comment by sonyco-4u** [comment]
I am interested you reach out to me on Whatsapp +2347060787395

**Comment by joemasilotti** [comment]
Closed via #845.
